# -*- coding: utf-8 -*-
"""Drowsiness_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXDvt2ZUUVFKabsJx_wcH7XuEfDTNMPE

Step 0: Install requirements
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import pandas as pd
import imutils
import dlib
import random

from tensorflow.keras.layers import Input, Conv2D, BatchNormalization, Dropout, Flatten, Dense, MaxPool2D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam, SGD
from sklearn.metrics import classification_report
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.regularizers import l2
from imutils.face_utils import FaceAligner
from imutils.face_utils import rect_to_bb

"""Step 1: Upload Dataset to Google Drive"""

data = np.load('/content/drive/MyDrive/driver_drowsiness_detection/dataset_compressed.npz', allow_pickle=True)
X = data['arr_0']
Y = data['arr_1']

X = list(X)
Y = list(Y)
print(len(X))
print(len(Y))

print(np.unique(Y))
plt.figure(figsize=(10, 10))
for i in range(16):
    idx = random.randint(0, len(X) - 1)
    img = X[idx]
    label = Y[idx]

    plt.subplot(4, 4, i + 1)
    if img.ndim == 2:  # grayscale
        plt.imshow(img, cmap='gray')
    else:              # RGB
        plt.imshow(img)
    plt.title(str(label))
    plt.axis('off')

plt.tight_layout()
plt.show()

"""Step 2: Data Preprocessing"""

label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)
print(Y.shape)
print(set(Y))

unique_classes, counts = np.unique(Y, return_counts=True)
for cls, count in zip(unique_classes, counts):
    label = label_encoder.inverse_transform([cls])[0] # Decode the label back to original string
    print(f"Number of images for '{label}': {count}")

for i in range(len(X)):
    img = X[i]
    img = cv2.resize(img, (32, 32))
    X[i] = img

print(len(X))
print(X[0].shape)

label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)
print(Y.shape)
print(Y[0])
print(set(Y))

X = np.array(X)
Y = np.array(Y)
print(X.shape)
print(Y.shape)

"""Delete not face image"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print("Train set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])

print("Train set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])
Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)

print("Y_train shape after one-hot encoding:", Y_train.shape)
print("Y_test shape after one-hot encoding:", Y_test.shape)

figure1 = plt.figure(figsize=(5, 5))
idx_closed = np.where(Y==0)
img_closed = X[idx_closed[0][1]]
plt.imshow(img_closed)
plt.title('Image of Closed Eye representing Driver is sleeping')
plt.axis('off')
plt.show()

figure2 = plt.figure(figsize=(5, 5))
idx_open = np.where(Y==1)
img_open = X[idx_open[0][1]]
plt.imshow(img_open)
plt.title('Image of Open Eye representing Driver is not sleeping')
plt.axis('off')
plt.show()

def driver_drowsiness_model(input_shape=(32, 32, 3)):
    model = Sequential()
    model.add(Input(shape=input_shape))

    filters = [16, 32, 64]
    for f in filters:
        model.add(Conv2D(f, (3, 3), padding='same', activation='relu'))
        model.add(BatchNormalization())
        model.add(MaxPool2D(pool_size=(2, 2)))

    model.add(Flatten())
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(0.4))  # Moderate dropout to prevent overfitting

    model.add(Dense(2, activation='softmax'))

    optimizer = Adam(learning_rate=0.01)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

    return model
model= driver_drowsiness_model(input_shape=(32, 32, 3))
model.summary()

aug = ImageDataGenerator(rotation_range=20, zoom_range=0.2, horizontal_flip=True)
hist = model.fit(aug.flow(X_train, Y_train, batch_size=128), batch_size=16, epochs=20, validation_data=(X_test, Y_test))

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(hist.history['loss'], label='Training loss')
plt.plot(hist.history['val_loss'], label='Validation loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.legend(); plt.grid(True)

plt.subplot(1,2,2)
plt.plot(hist.history['accuracy'], label='Training Accuracy')
plt.plot(hist.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch'); plt.ylabel('Accuracy')
plt.legend(); plt.grid(True)

plt.tight_layout()
plt.show()

train_loss, train_accuracy = model.evaluate(X_train, Y_train, verbose=0)
test_loss, test_accuracy = model.evaluate(X_test, Y_test, verbose=0)

print(f"Training loss: {train_loss * 100:.2f}%")
print(f"Testing loss: {test_loss * 100:.2f}%")

print(f"Training accuracy: {train_accuracy * 100:.2f}%")
print(f"Testing accuracy: {test_accuracy * 100:.2f}%")

y_pred_prob = model.predict(X_test) #get predicted probabilities
y_pred_class = (y_pred_prob > 0.5).astype(int)  # Convert probabilities to class labels (0 or 1)

# Convert Y_test and y_pred_class back to single-label format
Y_test_single_label = np.argmax(Y_test, axis=1)
y_pred_class_single_label = np.argmax(y_pred_class, axis=1)

cm = confusion_matrix(Y_test_single_label, y_pred_class_single_label)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Purples',
    xticklabels=['Predicted Closed', 'Predicted Open'],
    yticklabels=['Actual Closed', 'Actual Open']
)
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

model.save('Driver_Drowsiness_Detection.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open('Driver_Drowsiness_Detection.tflite', 'wb') as f:
    f.write(tflite_model)

print("Model converted to TFLite format and saved as 'Driver_Drowsiness_Detection.tflite'")

def check_available(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print(f"Image not found: {image_path}")
        return None
    return image

def full_face_detection_pipeline(input_image_path):
    eye_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/driver_drowsiness_detection/haarcascade_eye.xml')
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor('/content/drive/MyDrive/driver_drowsiness_detection/shape_predictor_68_face_landmarks.dat')

    # Load the TFLite model
    interpreter = tf.lite.Interpreter(model_path='/content/Driver_Drowsiness_Detection.tflite')
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    output_path = '/content/drive/MyDrive/driver_drowsiness_detection/test_image_prediction.jpg'

    test_image = check_available(input_image_path)
    rects = detector(test_image, 2)

    faceAligned_gray = None
    avg_confidence = None
    detected_eyes = []

    if len(rects) == 0:
        print("No faces detected in the image.")
        cv2.imwrite(output_path, test_image)
        return output_path, faceAligned_gray, avg_confidence, detected_eyes

    for rect in rects:
        (x, y, w, h) = rect_to_bb(rect)
        faceAligned = test_image[y:y+h, x:x+w].copy()
        faceAligned_gray = cv2.cvtColor(faceAligned, cv2.COLOR_BGR2GRAY)

        eyes = eye_cascade.detectMultiScale(faceAligned_gray, 1.1, 6)
        predictions = []
        confidences = []
        for (ex, ey, ew, eh) in eyes:
            eye = faceAligned[ey:ey+eh, ex:ex+ew]
            detected_eyes.append(cv2.resize(eye, (32, 32))) # Store resized eye
            eye = cv2.resize(eye, (32, 32))
            eye = np.expand_dims(np.array(eye), axis=0).astype(np.float32) # Convert to float32

            # Set the tensor to the input data.
            interpreter.set_tensor(input_details[0]['index'], eye)

            # Run inference.
            interpreter.invoke()

            # Post-processing: get the output tensor
            output_data = interpreter.get_tensor(output_details[0]['index'])
            ypred_prob = output_data[0]

            ypred = np.argmax(ypred_prob)
            predictions.append(ypred)
            confidences.append(np.max(ypred_prob))

        # Decide label and color
        if all(pred == 0 for pred in predictions):
            label = "Sleepy"
            color = (0, 0, 255)  # Red
        else:
            label = "Not Sleeping"
            color = (0, 255, 0)  # Green

        # Draw rectangle and label
        cv2.rectangle(test_image, (x, y), (x+w, y+h), color, 8)
        cv2.putText(test_image, label, (x, y-10),
              cv2.FONT_HERSHEY_SIMPLEX, 1.5, color, 3)
        avg_confidence = np.mean(confidences) if confidences else 0


    cv2.imwrite(output_path, test_image)
    return output_path, faceAligned_gray, avg_confidence, detected_eyes

figure = plt.figure(figsize=(15, 5))
predicted_image_path, aligned_face, confidence, detected_eyes = full_face_detection_pipeline('/content/sleepy2.jpg')

plt.subplot(1, 3, 1)
if aligned_face is not None:
    plt.imshow(aligned_face, cmap='gray')
    plt.title('Aligned Face')
    plt.axis('off')

plt.subplot(1, 3, 2)
if detected_eyes:
    plt.imshow(detected_eyes[0]) # Display the first detected eye
    plt.title('Detected Eye')
    plt.axis('off')
else:
    plt.text(0.5, 0.5, 'No eyes detected', horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes)
    plt.title('Detected Eye')
    plt.axis('off')


plt.subplot(1, 3, 3)
predicted_image = cv2.imread(predicted_image_path)
predicted_image = cv2.cvtColor(predicted_image, cv2.COLOR_BGR2RGB)
plt.imshow(predicted_image)
plt.axis('off')


plt.tight_layout()
plt.show()